// Feature Question List
export const CLEAR_QUESTION_LIST = 'CLEAR_FEATUREQUESTION';
export const Get_FEATUREQUESTION = 'Get_FEATUREQUESTION';
export const Get_FEATUREQUESTION_PENDING = 'Get_FEATUREQUESTION_PENDING';
export const Get_FEATUREQUESTION_FULFILLED = 'Get_FEATUREQUESTION_FULFILLED';
export const Get_FEATUREQUESTION_REJECTED = 'Get_FEATUREQUESTION_REJECTED';


//user details
export const CLEAR_USERDETAILS = 'CLEAR_USERDETAILS';
export const Get_USERDETAILS = 'Get_USERDETAILS';
// userdetail - user
export const Get_USER_PENDING = 'Get_USER_PENDING';
export const Get_USER_FULFILLED = 'Get_USER_FULFILLED';
export const Get_USER_REJECTED = 'Get_USER_REJECTED';
//userdetails - tags
export const Get_USERTAGS_PENDING = 'Get_USERTAGS_PENDING';
export const Get_USERTAGS_FULFILLED = 'Get_USERTAGS_FULFILLED';
export const Get_USERTAGS_REJECTED = 'Get_USERTAGS_REJECTED';
//userdetails - question
export const Get_USERQUESTIONS_PENDING = 'Get_USERQUESTIONS_PENDING';
export const Get_USERQUESTIONS_FULFILLED = 'Get_USERQUESTIONS_FULFILLED';
export const Get_USERQUESTIONS_REJECTED = 'Get_USERQUESTIONS_REJECTED';


